arch: s390x
services:
  - docker
env:
  global:
    - TEST_SCRIPT="test.sh"
    - TEST_DIR="$PWD/sid/slim"
    - BUILD_DIR="$PWD/sid/slim"
    - REPO="quay.io/ibm/debian"
    - TAG="$REPO:sid-slim"
before_script: 
  - docker login quay.io -u $ROBOT -p $ROBOT_TOKEN
  - cd $TEST_DIR && chmod +x $TEST_SCRIPT
script:
  - cd $BUILD_DIR && docker build . --tag $TAG
  - cd $TEST_DIR && bash $TEST_SCRIPT
after_script:
  - docker push $TAG
