arch: s390x
services:
  - docker
env:
  global:
    - BUILD_DIR="$PWD/docker-debian-artifacts/buster"
    - REPO="quay.io/ibmz/debian"
    - TAG="$REPO:buster"
before_script: 
  - cd $TEST_DIR && chmod +x $TEST_SCRIPT
  - docker login quay.io -u $ROBOT -p $ROBOT_TOKEN
script: 
  - docker build $BUILD_DIR --tag $TAG
after_script:
  - docker push $REPO
